### ISSUE TITLE
Issue #5 - User can search for entries by title.

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/code-journal#10]
## ✅ Task List

- [x] Create an input element for the search bar with label
  - [x]  The search bar  and button should only show up in the entries tab
- [x] Add an eventListener to the input when clicked it show the entries with title matching the search
  - [x] If partial of the entries title matches, then show the entry, ie “Entry - JavaScript” should show when user search “Entry”
  - [x] The search should find matched in both the title and the notes
  - [x] when the input is cleared out show the list of entries in full
- [x] Triple check CSS, remove what's not needed
- [x] Test if the new implementation work with old one, ie deleting/ editing an searched for entry
- [x] Fix all errors
