### ISSUE TITLE
Issue #6 - Bug fixes

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/code-journal#12]
## Task List
- [x] Changes the switch tab function to get data from data.view
- [x] remove switch to form and switch to entries function
- [x] when user load the page check data.view to see which view they are on and display it accordingly
- [x] add a toggle function for edit entry heading and the new entry heading
  - [x] they should never show up together
- [x] fix up html tags from button to anchor
- [x] changes css styling to give the user more space between entries.
