### ISSUE TITLE
Issue #7: User can add tags to an entry

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/code-journal#14]
## ✅ Task List
- [x] Create an input for user to enter in tags for each entry
- [x] Tags input is between photo url input and title
- [x] User can add multiple tags at once separating by comma
- [x] adjust javascript to make new tags work with old functionalities
  - [x] display the tags with the entries in entries list
  - [x] tags should appear under the title
    - [x] Make it look nice
    - [x] read the right version of font awesome
    - [x] tags should be save with data and loaded with its appropriate entries
  - [x] user can remove or add more tag when editing an entries
  - [x] update search function to show entries with tags matching the search
- [x] double check code, remove any unnecessary css, js, or html
- [x] test the site, if something break fix
