### ISSUE TITLE
Issue #8 - User can search entries by date created

### ISSUE THREAD

**Issue by Stran1025** [Stran1025/code-journal#17]
## Task List
 -  [x] Add a dateCreate property to the object data
 -  [x]  When user create a new post the attached the date to object data
 -  [x]  Add a new display on the entries on top of the pictures
    - [x] It should show month, date, year
    - [x] Mobile responsiveness make sure that the date is above the photos
 - [x] Allow the user to search for entries by date created
 - [x]  When user edits an entry make sure the date created and date display does not change
 - [x] Double check all features and styling
 - [x] Test all functionality making sure nothing is breaking
